### ISSUE TITLE
Duplicating effort

### ISSUE THREAD

**Issue by Cogitri** [alown/exheres#5]
Hey,

you're free to do what you want, but why don't you open a PR or something to my repo instead of duplicating the exheres/exlib in your repo? :)

**Comment by alown** [comment]
I apologize if my poor attempts at tweaking your exheres has upset you :)

The only excuse I will offer here, is that I don't generally keep the
packages in this repo in a hugely portable fashion, as I tend to be bodging
around an installation failure of some tool I have a desperate need to
use... (I also don't want to waste anybody else's time sending PRs of
changes with no re-usable value.)

If you think the modifications I have made to your exheres/exlibs are
actually worth upstreaming, I am happy to extract (and tidy them up) to
submit in your direction.

P.S. What led you to this repo? I haven't requested it for inclusion in
unavailable-unofficial, due to the above.

**Comment by Cogitri** [comment]
> I apologize if my poor attempts at tweaking your exheres has upset you :)

That's no what I meant, I'm by no means upset or anything. Sorry if this sounded harsh.

> I also don't want to waste anybody else's time sending PRs of
changes with no re-usable value.

Well, if you want the change it has some value :)

> I also don't want to waste anybody else's time sending PRs of
changes with no re-usable value.

Actually, I just searched for my name on github ( wanted to clone one of my repos ) and found this one on accident

> f you think the modifications I have made to your exheres/exlibs are
actually worth upstreaming, I am happy to extract (and tidy them up) to
submit in your direction.

Not sure if the `ffms` option is really necessary ( IIRC it's the only way to get sound with Aegisub ), but at least the `hunspell` and `fftw` flag would be nice to have ( although another name ( maybe `spell` and something other for fftw, not sure what it does, actually )).

**Comment by alown** [comment]
> Well, if you want the change it has some value :)

Okay. I will add tidying this up into a PR for you, to the list of
tasks to be done this weekend.

The complication with aegisub, is the addition of an [icu] flag to
dev-libs/boost (see my local bodged copy), I added to workaround
boost's icu auto-detection and build being partially broken. (Hence
why currently the aegisub+boost work is currently split other ~10
commits, many now unnecessary).

> Not sure if the ffms option is really necessary ( IIRC it's the only way to get sound with Aegisub ), but at least the hunspell and fftw flag would be nice to have ( although another name ( maybe spell and something other for fftw, not sure what it does, actually )).

You are correct ffms is required to interact with video or audio
content, but subtitle-timing etc. is still possible without, hence why
it is possible to build without.

fftw is a popular library for FFT calculations, optionally used by the
audio spectrum renderer.

**Comment by Cogitri** [comment]
> Okay. I will add tidying this up into a PR for you, to the list of tasks to be done this weekend. 

Thanks 👍
